version: "3.8"

services:
 app:
    container_name: backend
    restart: always
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile
    command: run
    volumes:
      - ./media:/app/media
      - /opt/backend/static:/app/backend/static
    env_file: .env.example
    ports:
      - 0.0.0.0:8000:8000
    links:
      - db
    depends_on:
      - db

 db:
    container_name: db
    restart: always
    image: postgres:12.4-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    env_file: .env.example
    expose:
      - 5432

volumes:
 postgres-data:
 static:
